server:
  port: 33062

spring:
  datasource:
    url: jdbc:mysql://office.nasbg.com:33062/bootcamp_java_23_august?createDatabaseIfNotExist=true
    username: bootcamp_java_23_august
    password: 8l38%OWQ8Egc2WysaS8W
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true