spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nasdataDB
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

bezkoder:
  app:
    jwtCookieName: bezkoder
    jwtSecret: ======================BezKoder=Spring===========================
    jwtExpirationMs: 30000