spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testDB
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

  server:
    forward-headers-strategy: framework
  mail:
    host: mail.nasbg.com
    port: 465
    username: "bootcamp@nasbg.com"
    password: '%61%,g]AI,g_'
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
          connection-timeout: 5000
          timeout: 5000
          write-timeout: 5000
