spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/moon
  username: bootcamp_java_23_august
  password: 8l38%OWQ8Egc2WysaS8W
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true